
using device cuda
Traceback (most recent call last):
  File "z:/prog/swevoice/train_2.py", line 131, in <module>
    main()
  File "z:/prog/swevoice/train_2.py", line 68, in main
    X_demo, Y_demo, _, _ = next(iter(val_loader))
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 34, in _pin_memory_loop
    data = pin_memory(data)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 62, in pin_memory
    return [pin_memory(sample) for sample in data]  # Backwards compatibility.
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 62, in <listcomp>
    return [pin_memory(sample) for sample in data]  # Backwards compatibility.
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 50, in pin_memory
    return data.pin_memory()
RuntimeError: cannot pin 'torch.cuda.FloatTensor' only dense CPU tensors can be pinned