
using device cuda
  0%|                                                                                                                                                                                                                                                                               | 0/480 [00:00<?, ?it/s]






Batch loss: 7.34404:   2%|█████▌                                                                                                                                                                                                                                           | 11/480 [00:40<28:46,  3.68s/it]
Traceback (most recent call last):
  File "z:/prog/swevoice/train_2.py", line 123, in <module>
    main()
  File "z:/prog/swevoice/train_2.py", line 83, in main
    preds, (_, _) = model(X, (h, c))
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "z:\prog\swevoice\model.py", line 77, in forward
    x, (h, c) = self.rec(x, hidden)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\rnn.py", line 761, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: CUDA out of memory. Tried to allocate 2.45 GiB (GPU 0; 6.00 GiB total capacity; 506.55 MiB already allocated; 1.04 GiB free; 2.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF